import {useCallback,useEffect,useRef,useState} from 'react';
import {Compass,BarChart3,Target,Newspaper,BookOpen,Landmark,Globe2,Menu,X,RefreshCw} from 'lucide-react';
import {LESSONS} from './catalog';
import {normalizeSearch} from './finance';
import {Chart,Title,External} from './ui';
import {date,fmt,storage} from './format';
import Planner from './Planner';
import Lab,{Projection} from './Lab';
import Sources from './Sources';
import Radar from './Radar.jsx';
import Education from './Education';
import {refreshPublic} from './live-data';
import './App.css';
const nav=[['overview','Visão geral',Compass],['market','Índices e tendências',BarChart3],['radar','Radar de ativos',Landmark],['goals','Meus objetivos',Target],['news','Notícias',Newspaper],['learn','Aprender',BookOpen],['lab','Analisar e projetar',Landmark],['sources','Fontes e ferramentas',Globe2],['education','Finalidade educativa',BookOpen]];
const levels=['Iniciante','Intermediário','Avançado'];
function Indicator({item,onClick}){const previous=item.history?.at(-2)?.value,change=Number.isFinite(previous)&&Number.isFinite(item.value)?item.value-previous:null;return <button className="indicator" onClick={onClick}><div className="indicator-top"><span>{item.name}</span><span className={`dot ${item.status==='ok'?'':'warn'}`}/></div><strong>{fmt(item.value)} <small>{item.unit}</small></strong><div className="indicator-bottom"><span>{date(item.date)}</span><span>{change===null?'—':`${change>0?'+':''}${fmt(change)} ${item.unit.includes('%')?'p.p.':''}`}</span></div><small>{item.country} · {item.provider} · {item.status==='ok'?'Último publicado':item.status==='old'?'Referência antiga':item.status==='cached'?'Dado anterior':'Indisponível'}</small></button>;}
function GeoFilter({geography,continent,setContinent,country,setCountry}){const continents=['Todos',...new Set(geography.map(g=>g[2]))];return <><select aria-label="Continente" value={continent} onChange={e=>{setContinent(e.target.value);setCountry('Todos');}}>{continents.map(c=><option key={c}>{c}</option>)}</select><select aria-label="País" value={country} onChange={e=>setCountry(e.target.value)}><option>Todos</option>{geography.filter(g=>continent==='Todos'||g[2]===continent).map(g=><option key={g[0]}>{g[1]}</option>)}</select></>;}
function News({snapshot,geography}){const [continent,setContinent]=useState('Todos'),[country,setCountry]=useState('Todos'),[q,setQ]=useState(''),[source,setSource]=useState('Todas'),[saved,setSaved]=useState(()=>storage.read('news',[])),[onlySaved,setOnlySaved]=useState(false),[warning,setWarning]=useState('');const list=(onlySaved?saved:snapshot.news||[]).filter(n=>(continent==='Todos'||n.continent===continent)&&(country==='Todos'||n.country===country)&&(source==='Todas'||n.source===source)&&normalizeSearch(n.title).includes(normalizeSearch(q)));const save=n=>{const next=saved.some(s=>s.id===n.id)?saved.filter(s=>s.id!==n.id):[n,...saved].slice(0,100);setSaved(next);if(!storage.write('news',next))setWarning('Favoritos não puderam ser salvos.');};return <><Title eyebrow="INFORMAÇÃO COM ORIGEM" title="Radar de notícias" description="Manchetes, países e perspectivas. Leia o contexto no veículo original."/><div className="toolbar"><input aria-label="Buscar notícia" placeholder="Inflação, bancos, empresas…" value={q} onChange={e=>setQ(e.target.value)}/><GeoFilter {...{geography,continent,setContinent,country,setCountry}}/><select aria-label="Veículo" value={source} onChange={e=>setSource(e.target.value)}>{['Todas',...new Set((snapshot.news||[]).map(n=>n.source))].map(s=><option key={s}>{s}</option>)}</select><button className="secondary" aria-pressed={onlySaved} onClick={()=>setOnlySaved(!onlySaved)}>{onlySaved?'Ver todas':`Salvas (${saved.length})`}</button></div><p className="muted">País é o contexto da busca, não a sede do veículo nem uma classificação editorial garantida. Manchetes em idioma original, indexadas via Google Notícias. Artigos podem exigir assinatura.</p>{snapshot.newsStatus?.some(n=>n.status!=='ok')&&<p className="notice">Algumas coletas de notícias falharam; a última edição disponível foi preservada.</p>}<p role="status">{warning}</p><div className="news-grid">{list.map(n=><article className="news-card" key={n.id}><div className="source-footer"><span className="eyebrow">{n.source}</span><button className="save-button" aria-label={saved.some(s=>s.id===n.id)?'Remover notícia salva':'Salvar notícia'} onClick={()=>save(n)}>{saved.some(s=>s.id===n.id)?'★':'☆'}</button></div><h3><a href={n.url} target="_blank" rel="noopener noreferrer">{n.title}</a></h3><div className="source-footer"><span>{date(n.date)} · {n.country}</span><External href={n.url}>Ler</External></div></article>)}</div>{!list.length&&<p className="empty">Nenhuma notícia para esta seleção. Altere os filtros ou consulte as fontes.</p>}</>;}
export default function App(){
 const [page,setPage]=useState('overview'),[level,setLevel]=useState(()=>storage.read('level','Iniciante')),[mobile,setMobile]=useState(false),[snapshot,setSnapshot]=useState({indicators:[],news:[],geography:[]}),[status,setStatus]=useState('Carregando automaticamente…'),[busy,setBusy]=useState(false),[indicator,setIndicator]=useState('selic'),[group,setGroup]=useState('Todos'),[query,setQuery]=useState(''),[continent,setContinent]=useState('Todos'),[country,setCountry]=useState('Brasil');
 const current=useRef({indicators:[],news:[],geography:[]}),running=useRef(false);const [now,setNow]=useState(()=>Date.now());
 const refresh=useCallback(async(direct=false)=>{if(running.current)return;running.current=true;setBusy(true);try{let next=current.current;const response=await fetch(`${import.meta.env.BASE_URL}data/snapshot.json?t=${Date.now()}`,{cache:'no-cache',signal:AbortSignal.timeout(20000)});if(!response.ok)throw new Error('Edição indisponível');const edition=await response.json();if(!Array.isArray(edition.indicators))throw new Error('Formato inválido');next={...edition,indicators:edition.indicators.map(i=>{const old=current.current.indicators.find(o=>o.id===i.id);return old?.fetchedAt>i.fetchedAt?old:i;})};if(direct){setStatus('Consultando fontes públicas…');const result=await refreshPublic(next);next=result.snapshot;setStatus(`${result.updated} indicadores consultados diretamente; ${result.failed} mantidos da edição. Notícias: última edição publicada.`);}else setStatus('Edição atualizada automaticamente. Fontes coletadas a cada 3h; consulta direta de indicadores a cada 15 min.');current.current=next;setSnapshot(next);}catch{setStatus('Não foi possível atualizar. Últimos dados carregados preservados; confira as datas.');}finally{running.current=false;setBusy(false);setNow(Date.now());}},[]);
 
 useEffect(()=>{const initial=setTimeout(()=>refresh(false),0);const timer=setInterval(()=>refresh(true),15*60000);const focus=()=>refresh(false);window.addEventListener('focus',focus);return()=>{clearTimeout(initial);clearInterval(timer);window.removeEventListener('focus',focus);};},[refresh]);
 const go=p=>{setPage(p);setMobile(false);window.scrollTo(0,0);};const selected=snapshot.indicators.find(i=>i.id===indicator);const geography=snapshot.geography||[];const filtered=snapshot.indicators.filter(i=>(group==='Todos'||i.group===group)&&(continent==='Todos'||i.continent===continent)&&(country==='Todos'||i.country===country)&&normalizeSearch(i.name).includes(normalizeSearch(query)));const old=snapshot.updatedAt&&now-Date.parse(snapshot.updatedAt)>12*3600000;
 return <div className="app"><a className="skip" href="#main">Pular para conteúdo</a><aside className={`sidebar ${mobile?'open':''}`}><a className="brand" href="#" onClick={e=>{e.preventDefault();go('overview');}}><span className="brand-icon">s↗</span><div>stock<span className="brand-light">analyzer</span><small>CLAREZA PARA O SEU FUTURO</small></div></a><button className="mobile-close" aria-label="Fechar menu" onClick={()=>setMobile(false)}><X/></button><p className="nav-caption">SEU ESPAÇO FINANCEIRO</p><nav>{nav.map(([id,name,Icon])=><button key={id} onClick={()=>go(id)} className={page===id?'active':''} aria-current={page===id?'page':undefined}><Icon size={18}/>{name}{page===id&&<span className="nav-dot"/>}</button>)}</nav><div className="sidebar-note"><span>UM PASSO DE CADA VEZ</span><h3>Invista primeiro<br/>em entender.</h3><p>Dados, contexto e um plano que faz sentido para você.</p><button onClick={()=>go('learn')}>Explorar aprendizado ↗</button></div><div className="sidebar-bottom"><span className="dot"/> Somente recursos gratuitos</div></aside>{mobile&&<button className="overlay" aria-label="Fechar navegação" onClick={()=>setMobile(false)}/>}
 <main id="main"><header><button className="mobile-toggle" aria-label="Abrir menu" onClick={()=>setMobile(true)}><Menu/></button><div className="breadcrumb">Meu radar <span>/ {nav.find(n=>n[0]===page)?.[1]}</span></div><label className="level"><span>Minha experiência</span><select aria-label="Minha experiência" value={level} onChange={e=>{setLevel(e.target.value);storage.write('level',e.target.value);}}>{levels.map(l=><option key={l}>{l}</option>)}</select></label><button className="refresh" onClick={()=>refresh(true)} disabled={busy}><RefreshCw size={14}/>{busy?'Atualizando…':'Atualizar agora'}</button></header><div className="content"><div className="edition" role="status"><span className={`dot ${old?'warn':''}`}/>{status}{snapshot.updatedAt&&<span> Edição: {new Date(snapshot.updatedAt).toLocaleString('pt-BR')}{old?' · EDIÇÃO ANTIGA':''}</span>}</div>
 {page==='overview'&&<><section className="hero"><div><p className="eyebrow">MENOS RUÍDO. MAIS PERSPECTIVA.</p><h1>Seu dinheiro.<br/><em>Um futuro com direção.</em></h1><p>Acompanhe a economia, entenda o mercado e transforme seus objetivos em planos. No seu ritmo.</p><button onClick={()=>go('goals')}>Planejar meu próximo objetivo ↗</button></div><div className="hero-art" aria-hidden="true"><div className="orbit one"/><div className="orbit two"/><div className="art-label">PERSPECTIVA<br/><strong>LONGO PRAZO ↗</strong></div><div className="bar b1"/><div className="bar b2"/><div className="bar b3"/><div className="bar b4"/><div className="art-bottom">CONSISTÊNCIA + TEMPO</div></div></section><Title eyebrow="DADOS QUE IMPORTAM" title="A economia, sem precisar procurar" description="Dados oficiais com fonte, data de referência e atualização automática."><button className="text-button" onClick={()=>go('market')}>Ver todos ↗</button></Title><div className="indicator-grid">{['selic','ipca12','usd','treasury'].map(id=>snapshot.indicators.find(i=>i.id===id)).filter(Boolean).map(i=><Indicator key={i.id} item={i} onClick={()=>{setIndicator(i.id);setCountry(i.country||'Todos');setContinent('Todos');go('market');}}/>)}</div><div className="overview-bottom"><div className="panel"><p className="eyebrow">SEU PRÓXIMO PASSO · {level.toUpperCase()}</p><h3>{LESSONS.find(l=>l.level===level)?.title}</h3><p>{LESSONS.find(l=>l.level===level)?.body}</p><button className="text-button" onClick={()=>go('learn')}>Continuar aprendendo ↗</button></div><div className="panel dark-panel"><p className="eyebrow">ESCOLHA O SEU PORQUÊ</p><h3>Uma casa. Uma viagem.<br/>Mais liberdade.</h3><p>12 objetivos, hipóteses transparentes e uma visão do caminho até lá.</p><button className="light-button" onClick={()=>go('goals')}>Explorar objetivos ↗</button></div></div></>}
 {page==='market'&&<><Title eyebrow="ATUALIZAÇÃO AUTOMÁTICA" title="Índices e tendências" description={`${snapshot.indicators.length} séries integradas. Filtre por continente, país e assunto; frequência da publicação depende da fonte.`}/><div className="toolbar"><input aria-label="Buscar indicador" placeholder="Selic, inflação, PIB…" value={query} onChange={e=>setQuery(e.target.value)}/><GeoFilter {...{geography,continent,setContinent,country,setCountry}}/><select aria-label="Grupo do indicador" value={group} onChange={e=>setGroup(e.target.value)}>{['Todos',...new Set(snapshot.indicators.map(i=>i.group))].map(g=><option key={g}>{g}</option>)}</select></div><div className="indicator-grid">{filtered.map(i=><Indicator key={i.id} item={i} onClick={()=>setIndicator(i.id)}/>)}</div>{!filtered.length&&<p className="empty">Nenhum indicador para esta seleção.</p>}{selected&&filtered.some(i=>i.id===selected.id)&&<><div className="panel"><Title eyebrow={`HISTÓRICO · ${selected.provider}`} title={selected.name} description={`${selected.country} · ${selected.unit}. ${selected.meaning}`}><External href={selected.sourceUrl}>Fonte original</External></Title>{selected.history.length?<Chart rows={selected.history}/>:<p>Sem dados; nenhum valor foi estimado.</p>}<p className="muted">Referência: {date(selected.date)}. Variação desde a observação anterior, em pontos percentuais para taxas. Dados anuais não são cotações atuais. {selected.status!=='ok'?'Confira a referência antiga ou a falha na coleta.':''}</p></div>{level==='Avançado'&&selected.history.length>=60&&selected.history.every(r=>r.value>0)&&<Projection key={selected.id} rows={selected.history}/>}</>}<div className="callout"><strong>Índices de bolsa com acesso condicionado</strong><p>Ibovespa, S&P 500, Nasdaq e outras bolsas podem exigir licença para redistribuição. Não são cotações ao vivo nesta edição pública. Consulte pelo conector pessoal local ou diretamente na fonte.</p><div className="chips"><External href="https://finance.yahoo.com/markets/world-indices/">Índices globais · Yahoo</External><External href="https://www.b3.com.br/pt_br/market-data-e-indices/indices/">B3</External><External href="https://www.investing.com/economic-calendar/">Calendário econômico</External></div></div></>}
 {page==='radar'&&<Radar snapshot={snapshot} onEducation={()=>go('education')}/>} {page==='education'&&<Education/>} {page==='goals'&&<Planner indicators={snapshot.indicators}/>}{page==='sources'&&<Sources/>}{page==='news'&&<News snapshot={snapshot} geography={geography}/>}{page==='lab'&&<Lab/>}
 {page==='learn'&&<><Title eyebrow="APRENDIZADO EM CADA ETAPA" title="Conhecimento que acompanha você" description="O nível adapta a trilha de aprendizado; não determina perfil de risco ou alocação."/><div className="tabs">{levels.map(l=><button className={level===l?'active':''} key={l} onClick={()=>{setLevel(l);storage.write('level',l);}}>{l}</button>)}</div><div className="lessons-grid">{LESSONS.filter(l=>l.level===level).map((l,i)=><article className="panel lesson" key={l.title}><span className="lesson-number">0{i+1}</span><h3>{l.title}</h3><p>{l.body}</p><div className="lesson-action"><strong>Na prática</strong><p>{l.action}</p></div></article>)}</div><div className="chips"><External href="https://www.gov.br/investidor/pt-br">CVM · Portal do Investidor</External><External href="https://www.investor.gov/introduction-investing">SEC · Investor.gov</External><External href="https://pages.stern.nyu.edu/~adamodar/">Damodaran · valuation</External></div></>}
 <footer><span>stockanalyzer ↗</span><p>Pesquisa e educação. Não é indicação de investimento, recomendação de compra/venda ou garantia de retorno. Projeções são estimativas; dados podem ter atraso.</p><button className="text-button" onClick={()=>go('sources')}>Fontes e recursos ↗</button></footer></div></main></div>;
}
