export const GOALS = [
  { id:'reserva', name:'Reserva de emergência', icon:'◈', target:30000, years:2, tip:'Estime meses de despesas essenciais. Considere liquidez, prazo de resgate e proteção do capital.' },
  { id:'aposentadoria', name:'Aposentadoria', icon:'☀', target:1500000, years:25, tip:'Planeje a renda complementar, a inflação e o risco de viver mais do que o patrimônio pode sustentar.' },
  { id:'casa', name:'Casa própria', icon:'⌂', target:200000, years:8, tip:'Diferencie entrada e preço total. Inclua documentação, mudança e uma margem para imprevistos.' },
  { id:'viagem', name:'Viagem', icon:'↗', target:25000, years:2, tip:'Defina moeda de destino, passagens, hospedagem e margem cambial. O câmbio pode mudar o custo.' },
  { id:'educacao', name:'Educação', icon:'▤', target:80000, years:6, tip:'Inclua mensalidades, materiais e custo de vida. As despesas educacionais podem subir acima do IPCA.' },
  { id:'carro', name:'Veículo', icon:'→', target:90000, years:4, tip:'Some seguro, manutenção e impostos ao preço. Compare custo total de compra e financiamento.' },
  { id:'negocio', name:'Abrir um negócio', icon:'▥', target:120000, years:5, tip:'Separe investimento inicial, capital de giro e reserva pessoal. O retorno do negócio é incerto.' },
  { id:'liberdade', name:'Independência financeira', icon:'∞', target:2000000, years:20, tip:'Revise despesas, impostos, retiradas e fontes de renda. Um patrimônio alvo não garante renda perpétua.' },
  { id:'familia', name:'Família e filhos', icon:'♡', target:100000, years:10, tip:'Divida despesas de curto prazo e metas futuras. Atualize o orçamento ao longo da vida.' },
  { id:'saude', name:'Saúde e cuidados', icon:'+', target:50000, years:3, tip:'Considere cobertura, franquias e cuidados prolongados. Evite depender de vender ativos em uma queda.' },
  { id:'dividas', name:'Quitar dívidas', icon:'✓', target:20000, years:2, tip:'Este cálculo projeta acumulação, não amortização de dívida. Compare o CET da dívida com o retorno líquido incerto.' },
  { id:'outro', name:'Objetivo personalizado', icon:'✧', target:50000, years:5, tip:'Escolha um valor em dinheiro de hoje e um prazo. Revise hipóteses de retorno, inflação e aportes.' },
];

const source = (name, group, url, description, access='Leitura na fonte', region='Global') => ({ name, group, url, description, access, region });
export const SOURCES = [
 source('Yahoo Finance','Mercado e ferramentas','https://finance.yahoo.com/','Cotações, histórico, resultados e listas de ativos. Integração local opcional via yfinance para pesquisa pessoal.','Site + conector local'),
 source('Bloomberg','Jornalismo','https://www.bloomberg.com/markets','Mercados e economia; dados profissionais exigem licença própria.','Assinatura / licença'),
 source('Reuters','Jornalismo','https://www.reuters.com/markets/','Agência internacional: empresas, mercados e geopolítica.','Acesso pode variar'),
 source('Financial Times','Jornalismo','https://www.ft.com/markets','Mercados, empresas e análises internacionais.','Assinatura'),
 source('The Wall Street Journal','Jornalismo','https://www.wsj.com/finance','Empresas e mercados financeiros.','Assinatura'),
 source('The Economist','Jornalismo','https://www.economist.com/finance-and-economics','Contexto econômico e análise de longo prazo.','Assinatura'),
 source('CNBC','Jornalismo','https://www.cnbc.com/markets/','Cobertura de bolsas e negócios. Manchetes no radar.','RSS / site'),
 source('MarketWatch','Jornalismo','https://www.marketwatch.com/','Portal financeiro, não é um banco. Mercados e finanças pessoais.','Acesso misto'),
 source('Valor Econômico','Jornalismo','https://valor.globo.com/financas/','Empresas, macroeconomia e finanças brasileiras.','Assinatura','Brasil'),
 source('InfoMoney','Jornalismo','https://www.infomoney.com.br/','Mercados e educação financeira no Brasil.','Acesso misto','Brasil'),
 source('Brazil Journal','Jornalismo','https://braziljournal.com/','Negócios e empresas brasileiras.','Site','Brasil'),
 source('Banco Central do Brasil','Dados e instituições','https://www.bcb.gov.br/','Selic, câmbio, séries SGS e expectativas Focus. Séries oficiais integradas ao painel.','API aberta','Brasil'),
 source('IBGE','Dados e instituições','https://www.ibge.gov.br/','Inflação, emprego, atividade e estatísticas oficiais.','Dados abertos','Brasil'),
 source('CVM','Dados e instituições','https://www.gov.br/cvm/pt-br','Regulador, informações de emissores e educação do investidor.','Dados abertos','Brasil'),
 source('B3','Dados e instituições','https://www.b3.com.br/pt_br/','Bolsa brasileira: produtos, índices e calendários. Dados sujeitos a condições de uso.','Site / licença','Brasil'),
 source('Tesouro Direto','Dados e instituições','https://www.tesourodireto.com.br/','Títulos públicos, preços e material educativo. Taxas variam diariamente.','Site','Brasil'),
 source('Federal Reserve / FRED','Dados e instituições','https://fred.stlouisfed.org/','Séries macroeconômicas dos EUA e outras economias. Observe a licença de cada série.','Site / API com chave','EUA'),
 source('SEC / EDGAR','Dados e instituições','https://www.sec.gov/edgar/search/','Demonstrações, fatos relevantes e documentos de empresas dos EUA.','Dados abertos','EUA'),
 source('Banco Central Europeu','Dados e instituições','https://data.ecb.europa.eu/','Taxas, câmbio e estatísticas da área do euro.','Dados abertos','Europa'),
 source('FMI','Dados e instituições','https://www.imf.org/en/Publications/WEO','World Economic Outlook: projeções macro, cenários e riscos.','Relatórios'),
 source('Banco Mundial','Dados e instituições','https://data.worldbank.org/','Indicadores econômicos e de desenvolvimento.','API aberta'),
 source('OCDE','Dados e instituições','https://data-explorer.oecd.org/','Dados comparáveis de economias e políticas públicas.','Dados abertos'),
 source('BIS','Dados e instituições','https://www.bis.org/','Banco de Compensações Internacionais: crédito, estabilidade e estatísticas.','Relatórios'),
 source('Itaú BBA','Bancos e research','https://www.itau.com.br/itaubba-pt/analises-economicas','Análises macroeconômicas e projeções.','Research público','Brasil'),
 source('Bradesco Economia','Bancos e research','https://www.economiaemdia.com.br/','Conjuntura, indicadores e projeções econômicas.','Research público','Brasil'),
 source('Santander Research','Bancos e research','https://www.santander.com.br/analise-economica','Economia brasileira e cenários.','Research público','Brasil'),
 source('BTG Pactual','Bancos e research','https://www.btgpactual.com/insights','Análises e conteúdo sobre economia e investimentos.','Acesso misto','Brasil'),
 source('Banco do Brasil','Bancos e research','https://www.bb.com.br/','Instituição financeira: consulte análises e produtos nos canais oficiais.','Site','Brasil'),
 source('J.P. Morgan','Bancos e research','https://www.jpmorgan.com/insights/global-research','Pesquisa global de mercados e economia.','Acesso misto'),
 source('Goldman Sachs','Bancos e research','https://www.goldmansachs.com/insights','Perspectivas econômicas e setoriais.','Acesso misto'),
 source('Morgan Stanley','Bancos e research','https://www.morganstanley.com/ideas','Mercados, tecnologia e economia.','Acesso misto'),
 source('UBS','Bancos e research','https://www.ubs.com/global/en/wealthmanagement/insights.html','Cenários e perspectivas globais.','Acesso misto'),
 source('BlackRock','Bancos e research','https://www.blackrock.com/corporate/insights/blackrock-investment-institute','Gestora: cenários e pesquisa de investimento.','Research público'),
 source('Vanguard','Bancos e research','https://investor.vanguard.com/investor-resources-education','Gestora: diversificação, custos e planejamento.','Educação'),
 source('S&P Global','Agências e risco','https://www.spglobal.com/ratings/','Ratings e pesquisa de crédito. Rating não garante ausência de perdas.','Acesso misto'),
 source('Moody’s','Agências e risco','https://www.moodys.com/','Análise de crédito e risco.','Acesso misto'),
 source('Fitch Ratings','Agências e risco','https://www.fitchratings.com/','Ratings corporativos, soberanos e financeiros.','Acesso misto'),
 source('Aswath Damodaran','Economistas e autores','https://pages.stern.nyu.edu/~adamodar/','Professor de finanças: valuation, bases de dados e aulas.','Público'),
 source('Claudia Sahm','Economistas e autores','https://stayathomemacro.substack.com/','Economista: política econômica, emprego e conjuntura dos EUA.','Acesso misto'),
 source('Noah Smith','Economistas e autores','https://www.noahpinion.blog/','Comentário econômico independente e políticas públicas.','Acesso misto'),
 source('Olivier Blanchard / PIIE','Economistas e autores','https://www.piie.com/experts/senior-research-staff/olivier-blanchard','Macroeconomia e política econômica em instituição de pesquisa.','Pesquisa'),
 source('Nouriel Roubini','Economistas e autores','https://nourielroubini.com/','Análises e opiniões macroeconômicas.','Acesso misto'),
 source('TradingView','Mercado e ferramentas','https://www.tradingview.com/','Gráficos, comparação e alertas no serviço externo.','Acesso misto'),
 source('Koyfin','Mercado e ferramentas','https://www.koyfin.com/','Painéis de mercado e análise fundamentalista.','Acesso misto'),
 source('FINVIZ','Mercado e ferramentas','https://finviz.com/','Screener e mapas de ações dos EUA.','Acesso misto','EUA'),
 source('Investing.com','Mercado e ferramentas','https://www.investing.com/economic-calendar/','Calendário econômico. Confira fuso, revisão e fonte de cada indicador.','Site'),
 source('Alpha Vantage','Mercado e ferramentas','https://www.alphavantage.co/documentation/','API documentada de mercado; requer chave e análise da licença.','API com chave'),
 source('brapi','Mercado e ferramentas','https://brapi.dev/docs','API para ativos brasileiros; planos e limites próprios.','API com chave','Brasil'),
 source('Investor.gov','Educação','https://www.investor.gov/free-financial-planning-tools','SEC: calculadoras de metas e juros compostos.','Público'),
 source('Portal do Investidor','Educação','https://www.gov.br/investidor/pt-br','CVM: conceitos, produtos, riscos e prevenção a fraudes.','Público','Brasil'),
 source('ANBIMA','Educação','https://www.anbima.com.br/','Indicadores, educação e informações sobre o mercado brasileiro.','Acesso misto','Brasil'),
];

export const LESSONS = [
 {level:'Iniciante', title:'Comece pelo seu orçamento', body:'Registre receitas, despesas essenciais e dívidas. O aporte sustentável vem do saldo real do orçamento, não da promessa de retorno.', action:'Planeje uma reserva de emergência antes de depender de ativos voláteis para despesas próximas.'},
 {level:'Iniciante', title:'Liquidez, risco e retorno', body:'Liquidez é a facilidade de transformar um investimento em dinheiro. Preço, crédito, inflação e câmbio podem provocar perdas. Retorno maior não é garantido por assumir mais risco.', action:'Compare o vencimento do investimento com a data do objetivo.'},
 {level:'Iniciante', title:'O efeito da inflação', body:'O saldo nominal mostra reais futuros. O saldo real representa o poder de compra de hoje. Uma meta de R$ 50 mil hoje pode custar mais no futuro.', action:'Experimente aumentar a inflação no simulador e observe o aporte necessário.'},
 {level:'Iniciante', title:'Juros compostos sem mágica', body:'Os juros incidem sobre o saldo acumulado. Aportes regulares, prazo e custos influenciam o resultado. As taxas inseridas no simulador são hipóteses.', action:'Compare um cenário com retorno zero antes de aumentar a hipótese de rendimento.'},
 {level:'Intermediário', title:'Diversificação de verdade', body:'Ter muitos ativos do mesmo setor pode manter a concentração. Observe emissores, países, moedas, classes e fatores de risco.', action:'Liste as exposições que se repetem na sua carteira.'},
 {level:'Intermediário', title:'Custos e retorno líquido', body:'Taxas, impostos, spreads e câmbio reduzem o saldo disponível. A tributação depende do produto e da situação do investidor.', action:'Teste o impacto de 1 ponto percentual de custo anual no planejamento.'},
 {level:'Intermediário', title:'Leia uma notícia de mercado', body:'Separe fato, expectativa e opinião. Confira data, fonte original, possíveis conflitos de interesse e se o mercado já incorporou o evento ao preço.', action:'Compare a mesma pauta em uma agência, um banco e uma fonte oficial.'},
 {level:'Intermediário', title:'Renda fixa também varia', body:'Títulos podem oscilar antes do vencimento. Crédito, prazo, indexador e liquidez importam. Garantias possuem regras e limites.', action:'Confira as condições oficiais do produto antes de comparar taxas.'},
 {level:'Avançado', title:'Volatilidade e drawdown', body:'Volatilidade mede dispersão dos retornos. Drawdown mede a queda desde o maior valor anterior. Nenhuma métrica resume sozinha o risco.', action:'Importe uma série diária no laboratório e compare as duas métricas.'},
 {level:'Avançado', title:'Evite vazamento no backtest', body:'Treine apenas com dados anteriores à previsão. Compare com uma referência simples, registre custos e evite selecionar uma estratégia só pelo melhor resultado passado.', action:'Use separação cronológica e avaliação fora da amostra.'},
 {level:'Avançado', title:'Valuation é um conjunto de hipóteses', body:'Fluxo de caixa, crescimento e taxa de desconto determinam estimativas. Uma pequena mudança pode alterar muito o valor calculado.', action:'Faça análise de sensibilidade e consulte demonstrações na CVM ou SEC.'},
 {level:'Avançado', title:'Aposentadoria e sequência de retornos', body:'Perdas no começo das retiradas podem prejudicar a duração do patrimônio. Uma taxa de retirada constante é uma simplificação, não uma garantia.', action:'Varie a taxa de retirada e inclua outras fontes de renda no seu plano.'},
];
