import {useState} from 'react';
import {parseCSV} from './finance';
import {compareHistories} from './comparison';
import {fmt,date} from './format';
import {ASSETS} from './assets';
export default function Comparison({rows,label,symbol,periods}){const [alternatives,setAlternatives]=useState([]),[currency,setCurrency]=useState(ASSETS.find(a=>a.symbol===symbol)?.currency||'BRL'),[tolerance,setTolerance]=useState(1),[error,setError]=useState(''),[busy,setBusy]=useState(false);let result,comparisonError;try{if(alternatives.length)result=compareHistories({name:label,rows,currency},alternatives,periods,tolerance);}catch(e){comparisonError=e.message;}
 const add=async e=>{try{const files=[...e.target.files];if(files.length+alternatives.length>5)throw new Error('Limite de cinco alternativas.');const items=[];for(const f of files){if(f.size>2e6)throw new Error('Limite de 2 MB por arquivo.');items.push({name:f.name,rows:parseCSV(await f.text()),currency});}setAlternatives([...alternatives,...items]);setError('');}catch(err){setError(err.message);}e.target.value='';};
 const automatic=async()=>{setBusy(true);setError('');try{const api=import.meta.env.VITE_API_URL;if(!api)throw new Error('Comparação automática de cotações exige o conector local. Aqui você pode comparar CSVs gratuitamente ou usar o gráfico externo.');const asset=ASSETS.find(a=>a.symbol===symbol);const peers=ASSETS.filter(a=>a.symbol!==symbol&&a.type===asset?.type&&a.currency===currency&&a.country===asset?.country).slice(0,4);if(!peers.length)throw new Error('Sem pares no catálogo. Importe históricos comparáveis.');const responses=await Promise.allSettled(peers.map(async a=>{const r=await fetch(`${api}/api/stocks/history?ticker=${encodeURIComponent(a.symbol)}&period=1y`,{signal:AbortSignal.timeout(35000)});const data=await r.json();if(!r.ok)throw new Error('Histórico indisponível');return {name:a.symbol,rows:data.history,currency:data.currency};}));const good=responses.filter(r=>r.status==='fulfilled').map(r=>r.value);setAlternatives(good);setError(`${good.length} alternativas carregadas; ${responses.length-good.length} indisponíveis. Seleção por classe, país e moeda, sem recomendação.`);}catch(err){setError(err.message);}finally{setBusy(false);}};
 return <div className="panel"><h3>Compare rentabilidade passada e risco</h3><p className="muted">Datas comuns a todos os históricos, mesma moeda e mesma frequência. O primeiro histórico é a referência. Preços devem usar o mesmo tratamento de proventos. Mais rentabilidade passada não significa melhor investimento.</p><div className="toolbar"><label className="field">Moeda dos CSVs<select aria-label="Moeda da comparação" value={currency} onChange={e=>{setCurrency(e.target.value);setAlternatives([]);}}>{['BRL','USD','EUR','GBP','JPY','AUD','CAD','ZAR'].map(c=><option key={c}>{c}</option>)}</select></label><label className="field">Faixa semelhante (p.p.)<input type="number" aria-label="Tolerância da comparação" min={0} max={10} step={.1} value={tolerance} onChange={e=>setTolerance(Number(e.target.value))}/></label><label className="upload">Adicionar alternativas CSV<input aria-label="Importar alternativas CSV" type="file" multiple accept=".csv" onChange={add}/></label><button className="secondary" disabled={busy} onClick={automatic}>{busy?'Comparando…':'Buscar alternativas · local'}</button><button className="text-button" onClick={()=>setAlternatives([])}>Limpar</button></div>{error&&<p role="status">{error}</p>}{comparisonError&&<p role="alert">{comparisonError}</p>}{result&&<><p className="muted">{date(result.dates[0])} a {date(result.dates.at(-1))} · {result.dates.length} observações comuns · {result.currency}</p><div className="table-scroll"><table><thead><tr><th>Histórico</th><th>Rentabilidade</th><th>Comparação</th><th>Volatilidade anual</th><th>Drawdown</th></tr></thead><tbody>{result.results.map((r,i)=><tr key={i}><td>{r.name}</td><td>{fmt(r.returnPct)}%</td><td>{r.relation}</td><td>{fmt(r.volatility)}%</td><td>{fmt(r.drawdown)}%</td></tr>)}</tbody></table></div>{result.excluded.length>0&&<p>Excluídos por moeda diferente: {result.excluded.join(', ')}</p>}<p className="notice">Resultado histórico, sem indicação de compra/venda e sem garantia de rentabilidade futura. Não inclui custos, impostos ou conversão cambial.</p></>}</div>;}
