import {Title,External} from './ui';
import {CLASSES} from './radar';
export default function Education(){return <>
  <Title eyebrow="FINALIDADE E METODOLOGIA" title="Educação, sem recomendação de investimento" description="O radar serve para aprender, comparar evidências e organizar pesquisa. Não indica compra, venda, alocação ou adequação ao seu perfil."/>
  <div className="callout"><strong>Nenhum ativo tem valorização ou renda garantida.</strong><p>“Destaque” significa que atende a um critério explícito na amostra observada. Não significa “melhor investimento”. O catálogo é uma seleção inicial, não a totalidade do mercado.</p></div>
  <div className="sources-grid">
    <article className="panel"><h3>Histórico não é previsão</h3><p>Retorno de 1 ano é acumulado; 3 e 5 anos são anualizados. Rankings só agrupam a mesma classe, moeda, data e metodologia. Preços ajustados e retorno total publicado pela gestora não são misturados.</p><p>Uma sequência de resultados positivos não elimina drawdowns. O retorno em reais de um ativo em dólar depende também do câmbio.</p></article>
    <article className="panel"><h3>Dividendos não são dinheiro grátis</h3><p>Dividendos, JCP, cupons, juros e distribuições têm regras diferentes. Pagamentos podem diminuir ou cessar. Um yield alto pode resultar de forte queda de preço; examine cobertura de caixa e pagamentos extraordinários.</p><p>Dividendos não são somados novamente ao retorno de um histórico já ajustado. Valores brutos não representam retorno líquido de custos e impostos.</p></article>
    <article className="panel"><h3>Opinião de analista não é certeza</h3><p>Preço-alvo é uma estimativa, com premissas e horizonte próprios. Uma casa não representa todo o mercado. A razão da tese e o risco contrário são mostrados juntos.</p><p>Sem fonte, data ou tese publicada, o sistema informa indisponibilidade. Um modelo estatístico não é chamado de consenso de analistas.</p></article>
    <article className="panel"><h3>Fontes e atualização</h3><p>As referências editoriais são datadas e não se renovam sozinhas. Notícias acompanham a edição automática. O conector Yahoo é opcional, para pesquisa pessoal local, com consulta de 15 em 15 minutos enquanto a aba estiver aberta.</p><p>Dados ausentes ficam vazios; nunca são convertidos em yield zero, ausência de risco ou sinal de compra. Fundos privados e produtos sem código público precisam de documentos do emissor.</p></article>
  </div>
  <div className="panel"><h3>Como cada classe pode produzir retorno</h3><div className="table-scroll"><table><thead><tr><th>Classe</th><th>Renda</th><th>O que investigar</th></tr></thead><tbody>{CLASSES.map(([name,income,check])=><tr key={name}><td>{name}</td><td>{income}</td><td>{check}</td></tr>)}</tbody></table></div></div>
  <div className="chips"><External href="https://www.gov.br/investidor/pt-br">CVM · educação financeira</External><External href="https://www.investor.gov/introduction-investing">Investor.gov</External></div>
</>;}
