import Discovery from './Discovery';
import Comparison from './Comparison.jsx';
import {useState} from 'react';
import {parseCSV,priceMetrics} from './finance';
import {forecast} from './forecast';
import {Title,Chart,External} from './ui';
import {fmt,date,download} from './format';
const colors=['#16796d','#c18447','#6b74b5','#a57399','#789957'];
export function Projection({rows}){const [steps,setSteps]=useState(20),[show,setShow]=useState(false);let result,error;try{if(show)result=forecast(rows,steps);}catch(e){error=e.message;}return <div className="panel"><h3>Projeção futura · estudo estatístico</h3><p className="notice">Não é indicação de investimento nem garantia de retorno. Nenhum modelo prevê consistentemente o mercado. O menor erro histórico não garante o melhor resultado futuro.</p><div className="toolbar"><label className="field">Horizonte (observações)<input aria-label="Horizonte da projeção" type="number" min={1} max={90} value={steps} onChange={e=>setSteps(Number(e.target.value))}/></label><button onClick={()=>setShow(true)}>Comparar 5 modelos</button></div>{error&&<p role="alert">{error}</p>}{result&&<><p>Menor MAE nesta validação: <strong>{result.best.name}</strong>.</p><Chart rows={result.series} x="step" series={result.results.map((r,i)=>[r.id,r.name,colors[i]])}/><div className="table-scroll"><table><thead><tr><th>Modelo</th><th>MAE</th><th>RMSE</th><th>MAPE</th><th>Última projeção</th></tr></thead><tbody>{result.results.map(r=><tr key={r.id}><td>{r.name}</td><td>{fmt(r.mae)}</td><td>{fmt(r.rmse)}</td><td>{fmt(r.mape)}%</td><td>{fmt(r.future.at(-1))}</td></tr>)}</tbody></table></div><p className="muted">Validação com origem deslizante: {result.folds} blocos cronológicos de {result.horizon} observações, {result.observations} pontos de teste. Cada treino só usa dados anteriores ao bloco. MAE/RMSE na unidade da série. Parâmetros fixos: SES α=0,3; Holt α=0,3, β=0,1, amortecimento=0,9. Datas futuras são observações, não datas de pregão. Não inclui eventos, custos, intervalos probabilísticos ou alterações de regime. Teste pode ter horizonte menor que a projeção.</p><button className="secondary" onClick={()=>download('projecoes-estatisticas.csv','Observacao,'+result.results.map(r=>r.name).join(',')+'\n'+result.series.map(r=>[r.step,...result.results.map(m=>r[m.id])].join(',')).join('\n'))}>Exportar projeções</button></>}</div>;}
export default function Lab(){const [rows,setRows]=useState([]),[symbol,setSymbol]=useState('PETR4.SA'),[periods,setPeriods]=useState(252),[label,setLabel]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false);const metrics=rows.length?priceMetrics(rows,periods):null;
 const importFile=async e=>{const file=e.target.files?.[0];if(!file)return;try{if(file.size>2e6)throw new Error('Limite de 2 MB.');setRows(parseCSV(await file.text()));setLabel(`${file.name} · importado por você`);setError('');}catch(err){setRows([]);setError(err.message);}e.target.value='';};
 const load=async()=>{setBusy(true);setRows([]);setError('');try{const api=import.meta.env.VITE_API_URL;if(!api)throw new Error('Use CSV nesta edição pública. A consulta Yahoo requer a versão local configurada.');const response=await fetch(`${api}/api/stocks/history?ticker=${encodeURIComponent(symbol)}&period=1y`,{signal:AbortSignal.timeout(35000)});const data=await response.json();if(!response.ok)throw new Error(data.detail||'Falha ao consultar.');if(!Array.isArray(data.history)||data.history.length<3)throw new Error('Histórico insuficiente.');setRows(data.history);setLabel(`${data.symbol} · ${data.currency} · Yahoo via yfinance · ${date(data.asOf)}`);}catch(err){setError(err.message);}finally{setBusy(false);}};
 return <><Title eyebrow="PESQUISA DE ATIVOS" title="Entenda antes de decidir" description="Histórico, risco e projeções. Seus arquivos são processados somente neste navegador."/><Discovery onSelect={a=>{setSymbol(a.symbol);setRows([]);setLabel('');setError('');}}/><div className="panel"><div className="toolbar"><label className="field">Ativo<input aria-label="Código do ativo" maxLength={20} value={symbol} onChange={e=>setSymbol(e.target.value.toUpperCase())}/></label><button onClick={load} disabled={busy}>{busy?'Consultando…':'Consultar Yahoo · local'}</button><label className="upload">Importar CSV<input aria-label="Importar histórico CSV" type="file" accept=".csv,text/csv" onChange={importFile}/></label><select aria-label="Frequência do histórico" value={periods} onChange={e=>setPeriods(Number(e.target.value))}><option value={252}>Diário · 252 pregões/ano</option><option value={365}>Diário · cripto 365 dias</option><option value={12}>Mensal · 12 observações</option></select></div><p className="muted">Colunas Date,Close ou Data;Fechamento. Datas AAAA-MM-DD, preços positivos e sem duplicatas. Ajuste frequência e use preços ajustados de forma consistente.</p><div className="chips"><External href={`https://finance.yahoo.com/quote/${encodeURIComponent(symbol)}/history/`}>Histórico no Yahoo</External><External href="https://www.tradingview.com/">TradingView</External><External href="https://www.sec.gov/edgar/search/">SEC / EDGAR</External><External href="https://www.gov.br/cvm/pt-br">CVM</External></div>{error&&<p role="alert" className="notice">{error}</p>}</div>{metrics?<><div className="metric-grid">{[['Variação no período',metrics.returnPct],['Volatilidade anualizada',metrics.volatility],['Maior queda desde um pico',metrics.drawdown]].map(([name,value])=><div className="panel metric" key={name}><small>{name}</small><strong>{fmt(value)}%</strong></div>)}</div><div className="panel"><h3>{label}</h3><p className="muted">{rows.length} observações · {date(rows[0].date)} a {date(rows.at(-1).date)}</p><Chart rows={metrics.series} series={[["close","Fechamento","#16796d"],["average","Média de 20 observações","#c18a56"]]}/><p className="muted">Volatilidade = desvio padrão amostral dos retornos simples × raiz da frequência anual. Drawdown = queda desde o maior fechamento anterior. Lacunas podem distorcer anualização. Proventos não incluídos se não refletidos na série.</p></div><Projection key={label} rows={rows}/><Comparison key={label} rows={rows} label={label} symbol={symbol} periods={periods}/></>:<div className="empty"><h3>Seu estudo começa com dados</h3><p>Importe um CSV ou use o conector local. Nenhuma cotação é inventada.</p></div>}</>;
}
