import {useState} from 'react';
import {GOALS} from './catalog';
import {projectGoal,retirementCapital} from './finance';
import {Title,Field,Chart} from './ui';
import {storage,money,fmt,date,download} from './format';
export default function Planner({indicators}){
 const [goal,setGoal]=useState(()=>storage.read('goal','reserva')),[v,setV]=useState(()=>storage.read('plan',{initial:10000,monthly:800,years:2,target:30000,rate:6,inflation:4,fee:0,tax:0})),[income,setIncome]=useState(5000),[withdrawal,setWithdrawal]=useState(4),[message,setMessage]=useState(''),[saved,setSaved]=useState(()=>storage.read('saved',[]));
 const selected=GOALS.find(g=>g.id===goal)||GOALS[0];const set=(key,value)=>setV({...v,[key]:value});let result,error;try{result=projectGoal(v);}catch(e){error=e.message;}
 const save=()=>{if(!result)return;const next=[...saved.filter(s=>s.id!==goal),{id:goal,name:selected.name,values:v}];setSaved(next);setMessage(storage.write('saved',next)&&storage.write('plan',v)&&storage.write('goal',goal)?'Plano salvo neste navegador.':'Não foi possível salvar. Exporte o CSV.');};
 const ipca=indicators.find(i=>i.id==='ipca12');
 return <><Title eyebrow="PLANEJAMENTO COM PROPÓSITO" title="O que você quer conquistar?" description="12 objetivos. Valores de exemplo editáveis. Hipóteses de retorno, nunca promessas."/><div className="goals-grid">{GOALS.map(g=><button className={`goal-card ${g.id===goal?'selected':''}`} aria-pressed={g.id===goal} key={g.id} onClick={()=>{setGoal(g.id);setV({...v,target:g.target,years:g.years});setMessage('Valores de exemplo carregados. Ajuste à sua realidade.');}}><span>{g.icon}</span>{g.name}</button>)}</div><div className="callout"><strong>{selected.name}</strong><p>{selected.tip}</p></div>
 {goal==='aposentadoria'&&<div className="panel"><h3>Planeje a renda complementar</h3><div className="form-grid"><Field label="Renda mensal em reais de hoje" value={income} onChange={setIncome} min={0}/><Field label="Retirada anual hipotética (%)" value={withdrawal} onChange={setWithdrawal} min={1} max={10} step={.5}/></div><button onClick={()=>{try{set('target',retirementCapital(income,withdrawal));}catch(e){setMessage(e.message);}}}>Calcular capital alvo</button><p className="muted">Capital = renda mensal × 12 ÷ taxa de retirada. Não inclui INSS, longevidade ou sequência de retornos. A retirada não é garantida.</p></div>}
 <div className="planner-layout"><div className="panel"><h3>Seu ponto de partida</h3><div className="form-grid">{[['initial','Já guardado (R$)',0,1e10,100],['monthly','Aporte mensal (R$)',0,1e8,100],['target','Meta em dinheiro de hoje (R$)',0,1e11,1000],['years','Prazo (anos)',1,60,1],['rate','Retorno hipotético (% a.a.)',-50,50,.5],['inflation','Inflação hipotética (% a.a.)',-10,50,.5],['fee','Custo anual (%)',0,10,.1],['tax','Imposto sobre o ganho no resgate (%)',0,50,.5]].map(([key,label,min,max,step])=><Field key={key} label={label} value={v[key]} onChange={value=>set(key,value)} min={min} max={max} step={step}/>)}</div>{Number.isFinite(ipca?.value)&&<button className="text-button" onClick={()=>set('inflation',Math.round(ipca.value*100)/100)}>Usar IPCA 12m: {fmt(ipca.value)}% · {date(ipca.date)}</button>}<p className="muted">O indicador é atualizado automaticamente. A hipótese do plano só muda quando você escolhe usá-lo: inflação passada não prevê a futura.</p><div className="actions"><button onClick={save}>Salvar plano</button><button className="secondary" disabled={!result} onClick={()=>download(`plano-${goal}.csv`,'Ano,Saldo liquido,Aportes,Saldo real\n'+result.series.map(r=>[r.year,r.balance.toFixed(2),r.invested.toFixed(2),r.real.toFixed(2)].join(',')).join('\n'))}>Exportar CSV</button></div><p role="status">{message}</p></div><div className="panel">{error?<p role="alert">{error}</p>:<><div className="result-head"><p className="eyebrow">PROJEÇÃO HIPOTÉTICA</p><strong>{money(result.final)}</strong><p>{money(result.real)} em poder de compra de hoje</p></div><Chart rows={result.series} x="year" financial series={[["balance","Saldo líquido","#16796d"],["invested","Aportes","#95ac84"]]}/><div className="result-stats"><div><small>Meta corrigida pela inflação</small><strong>{money(result.futureTarget)}</strong></div><div><small>Aporte mensal calculado para a meta</small><strong>{money(result.required)}</strong></div></div><p className="notice">{result.reached?'A meta é atingida':'A meta não é atingida'} nesta hipótese. Não há garantia de resultado.</p></>}</div></div>
 {result&&<div className="panel"><h3>E se o retorno for diferente?</h3><div className="scenario-grid">{[Math.max(-50,v.rate-3),v.rate,Math.min(50,v.rate+3)].map((rate,i)=>{const r=projectGoal({...v,rate});return <div key={i}><small>{['Inferior','Central','Superior'][i]} · {fmt(rate)}% a.a.</small><strong>{money(r.final)}</strong><span>{money(r.real)} de hoje</span></div>;})}</div><p className="muted">Cenários determinísticos, não probabilidades. Aportes no fim do mês, taxas constantes, sem saques. Custo anual multiplicativo; imposto apenas sobre ganho positivo no resgate. Não representa todas as regras tributárias dos produtos.</p></div>}
 {saved.length>0&&<div className="panel"><h3>Planos salvos</h3><div className="chips">{saved.map(s=><button key={s.id} className="secondary" onClick={()=>{setGoal(s.id);setV(s.values);}}>{s.name} · {money(s.values.target)}</button>)}</div></div>}</>;
}
