export const CLASSES = [
  ['Ação', 'Dividendos e JCP', 'Lucro, geração de caixa, dívida e preço pago.'],
  ['ETF', 'Distribuição ou acumulação, conforme regulamento', 'Índice, custos, concentração e política de distribuição.'],
  ['FII / REIT', 'Rendimentos imobiliários', 'Vacância, inadimplência, contratos, dívida e sustentabilidade dos pagamentos.'],
  ['Fundo de investimento', 'Distribuição ou valorização da cota', 'Benchmark, taxas, prazo de resgate e retorno líquido; muitos fundos reinvestem a renda.'],
  ['Renda fixa pública', 'Juros e cupons, não dividendos', 'Vencimento, inflação, duration e marcação a mercado.'],
  ['Renda fixa privada', 'Juros e amortizações, não dividendos', 'Crédito do emissor, liquidez e garantias específicas do produto.'],
  ['Cripto', 'Sem dividendos societários; staking é outro mecanismo', 'Volatilidade, custódia, protocolo e riscos de contraparte.'],
  ['Commodities', 'O ativo físico não distribui dividendos', 'Oferta, demanda, custos de armazenagem e exposição por futuros.'],
  ['Câmbio', 'Sem dividendos', 'Diferencial de juros, fluxos, política monetária e custos da exposição.'],
  ['Índice', 'Referência de mercado, não produto investível', 'Metodologia e diferença entre índice de preços e de retorno total.'],
  ['Derivativo', 'Resultado contratual, não dividendos', 'Alavancagem, margem, vencimento e possibilidade de perdas elevadas.'],
  ['Alternativo / privado', 'Fluxos específicos do contrato', 'Avaliação pouco frequente, liquidez, estrutura jurídica e dados auditados.'],
];

export const WATCHLIST = [
  {symbol:'NTN-B · família',name:'Tesouro IPCA+ com Juros Semestrais',type:'Renda fixa pública',currency:'BRL',country:'Brasil',income:true,reason:'Referência para estudar renda periódica e proteção inflacionária. Escolha um vencimento e compare preço, taxa e fluxo de cupons no documento oficial; não há cotação automática desta família.',risk:'Venda antes do vencimento está sujeita à marcação a mercado; cupons exigem avaliar impostos e reinvestimento.',source:'Tesouro Direto',url:'https://www.tesourodireto.com.br/documents/d/guest/tesouro_ipca_juros_semestrais'},
  {symbol:'Debêntures · família',name:'Títulos de dívida corporativa',type:'Renda fixa privada',currency:'BRL',country:'Brasil',income:true,reason:'Pesquisar emissores, escrituras e cronogramas de juros e amortização. A renda depende do contrato; esta família não representa um título ou yield específico.',risk:'Risco de crédito e liquidez; examinar garantias e capacidade de pagamento de cada emissor.',source:'CVM · Portal do Investidor',url:'https://www.gov.br/investidor/pt-br/investir/tipos-de-investimentos/debentures'},
  {symbol:'Ouro físico',name:'Ouro como commodity',type:'Commodities',currency:'USD',country:'Global',income:false,reason:'Investigar oferta, demanda e juros reais. Referência de exposição ao metal; não gera dividendos e não equivale à cota de um ETF.',risk:'Oscilação de preço, câmbio, custos de guarda e negociação.',source:'Banco Mundial · Commodity Markets Outlook',url:'https://thedocs.worldbank.org/en/doc/f3138644a1e8e2bb631399ae11d6c408-0050012026/original/CMO-April-2026.pdf'},
  {symbol:'BRL=X',name:'Dólar / Real',type:'Câmbio',currency:'BRL',country:'Brasil',income:false,reason:'Observar diferencial de juros, fluxos e exposição cambial da carteira. Valorização do dólar não representa dividendos nem uma renda contratada.',risk:'A direção da cotação depende da moeda de referência; custos e produtos de exposição têm regras distintas.',source:'Banco Central do Brasil',url:'https://www.bcb.gov.br/estabilidadefinanceira/historicocotacoes'},
  {symbol:'^BVSP',name:'Ibovespa · referência de mercado',type:'Índice',currency:'BRL',country:'Brasil',income:false,reason:'Referência para comparar ações e fundos brasileiros. O índice é uma medida de desempenho; exposição investível depende de outro produto.',risk:'Composição e concentração mudam; retorno do produto pode diferir do índice por custos e metodologia.',source:'B3 · Ibovespa',url:'https://b3.com.br/pt_br/market-data-e-indices/indices/indices-amplos/ibovespa-b3.htm'},
  {symbol:'ES=F',name:'Futuro E-mini S&P 500',type:'Derivativo',currency:'USD',country:'Estados Unidos',income:false,reason:'Estudar exposição contratual, vencimento e margem. Histórico de contrato contínuo não equivale ao retorno de uma posição financiada e rolada.',risk:'Alavancagem e ajustes diários podem ampliar perdas; contratos e rolagens precisam de análise própria.',source:'CME Group',url:'https://www.cmegroup.com/markets/equities/sp/sandp-futures.html'},
  {symbol:'FIP · família',name:'Fundos de Investimento em Participações',type:'Alternativo / privado',currency:'BRL',country:'Brasil',income:null,reason:'Investigar participações em empresas, avaliações e fluxos de cada fundo. Distribuições e acesso dependem do regulamento; não há série pública uniforme para classificar esta família.',risk:'Baixa liquidez, avaliações pouco frequentes e incerteza no momento de saída.',source:'B3 · FIP',url:'https://www.b3.com.br/pt_br/produtos-e-servicos/negociacao/renda-variavel/fundos-de-investimento-em-participacoes-fip.htm'},
  {symbol:'SCHB',name:'Schwab U.S. Broad Market ETF',type:'ETF',currency:'USD',country:'Estados Unidos',income:true,reason:'Acompanha um índice amplo de ações americanas. Referência de crescimento diversificado para comparar estratégias de dividendos.',risk:'Exposição a ações; concentração e mudanças de avaliação afetam o resultado.',source:'Schwab Asset Management',url:'https://www.schwabassetmanagement.com/products/schb',observation:{asOf:'2026-08-31',r1:20.04,r3:20.64,r5:11.74,method:'Retorno total pelo preço de mercado; 3 e 5 anos anualizados.'}},
  {symbol:'SCHY',name:'Schwab International Dividend Equity ETF',type:'ETF',currency:'USD',country:'Estados Unidos',income:true,reason:'Estratégia de dividendos internacionais. Permite observar renda e crescimento fora da bolsa americana.',risk:'Exposição a outras moedas, países e setores; distribuição variável.',source:'Schwab Asset Management',url:'https://www.schwabassetmanagement.com/products/schy',observation:{asOf:'2026-08-31',r1:22.92,r3:16.84,r5:9.05,method:'Retorno total pelo preço de mercado; 3 e 5 anos anualizados.',payment:.3571,paymentDate:'2026-06-29'}},
  {symbol:'SCHD',name:'Schwab U.S. Dividend Equity ETF',type:'ETF',currency:'USD',country:'Estados Unidos',income:true,reason:'Índice de ações americanas com filtros de dividendos e fundamentos. Observar retorno total e concentração, além dos pagamentos.',risk:'Dividendos podem cair; concentração setorial e preço da cota oscilam.',source:'Schwab Asset Management',url:'https://www.schwabassetmanagement.com/products/schd',observation:{asOf:'2026-08-31',r1:29.53,r3:16.19,r5:10.01,method:'Retorno total pelo preço de mercado; 3 e 5 anos anualizados.',payment:0.2525,paymentDate:'2026-06-29'}},
  {symbol:'VIG',name:'Vanguard Dividend Appreciation ETF',type:'ETF',currency:'USD',country:'Estados Unidos',income:true,reason:'Acompanha empresas com histórico de aumento de dividendos. Essa política não garante crescimento futuro da renda ou das cotas.',risk:'Risco de ações e de avaliação; yield alto não é objetivo obrigatório.',source:'Vanguard',url:'https://advisors.vanguard.com/investments/products/vig/vanguard-dividend-appreciation-etf'},
  {symbol:'VYM',name:'Vanguard High Dividend Yield ETF',type:'ETF',currency:'USD',country:'Estados Unidos',income:true,reason:'Estratégia de ações de dividendos elevados. Avaliar sustentabilidade, diversificação e retorno total.',risk:'Yield elevado pode decorrer de queda do preço.',source:'Vanguard',url:'https://investor.vanguard.com/investment-products/etfs/profile/vym'},
  {symbol:'MSFT',name:'Microsoft',type:'Ação',currency:'USD',country:'Estados Unidos',income:true,reason:'Exemplo de empresa que declara dividendos e é acompanhada por analistas. Verificar caixa após investimentos, margens e avaliação.',risk:'Expectativas de IA, concorrência e despesas de infraestrutura podem afetar a tese.',source:'Microsoft Investor Relations',url:'https://www.microsoft.com/en-us/investor'},
  {symbol:'ITUB4.SA',name:'Itaú Unibanco',type:'Ação',currency:'BRL',country:'Brasil',income:true,reason:'Acompanhar proventos declarados, rentabilidade do banco, inadimplência e capital regulatório.',risk:'Dividendos e JCP dependem dos resultados e das decisões do emissor.',source:'Itaú RI',url:'https://www.itau.com.br/relacoes-com-investidores/'},
  {symbol:'PETR4.SA',name:'Petrobras',type:'Ação',currency:'BRL',country:'Brasil',income:true,reason:'Acompanhar fluxo de caixa, investimentos, petróleo e política de remuneração aos acionistas.',risk:'Proventos extraordinários não são uma renda recorrente garantida.',source:'Petrobras RI',url:'https://www.investidorpetrobras.com.br/'},
  {symbol:'HGLG11.SA',name:'FII HGLG11',type:'FII / REIT',currency:'BRL',country:'Brasil',income:true,reason:'Examinar relatório gerencial, ocupação, contratos e resultado distribuível.',risk:'Vacância, preços das cotas e eventos não recorrentes afetam rendimentos.',source:'CVM · consulta de fundos',url:'https://www.gov.br/cvm/pt-br/assuntos/regulados/consultas-por-participante/fundos-de-investimento'},
  {symbol:'O',name:'Realty Income',type:'FII / REIT',currency:'USD',country:'Estados Unidos',income:true,reason:'Examinar pagamentos anunciados, ocupação, dívida e cobertura por geração de caixa.',risk:'Juros e crédito dos locatários afetam avaliação e capacidade de distribuição.',source:'Realty Income',url:'https://www.realtyincome.com/investors'},
  {symbol:'VDIGX',name:'Vanguard Dividend Growth Fund',type:'Fundo de investimento',currency:'USD',country:'Estados Unidos',income:true,reason:'Fundo voltado ao crescimento de dividendos. Comparar a cota, distribuições, taxas e benchmark na mesma janela.',risk:'Gestão ativa pode ficar abaixo do benchmark; acesso depende da jurisdição.',source:'Vanguard',url:'https://investor.vanguard.com/investment-products/mutual-funds/profile/vdigx'},
  {symbol:'BND',name:'Vanguard Total Bond Market ETF',type:'ETF',currency:'USD',country:'Estados Unidos',income:true,reason:'Exposição a títulos de renda fixa; distribuições vêm da carteira de títulos, não de dividendos de empresas.',risk:'Duration, crédito e juros podem causar perda na cota.',source:'Vanguard',url:'https://advisors.vanguard.com/investments/products/bnd/vanguard-total-bond-market-etf'},
  {symbol:'BTC-USD',name:'Bitcoin',type:'Cripto',currency:'USD',country:'Global',income:false,reason:'Observar adoção, liquidez e risco; alta de preço não produz dividendos.',risk:'Volatilidade, custódia e risco de contraparte.',source:'CVM · criptoativos',url:'https://www.gov.br/investidor/pt-br/investir/tipos-de-investimentos/criptoativos'},
  {symbol:'GLD',name:'SPDR Gold Shares',type:'ETF',currency:'USD',country:'Estados Unidos',income:false,reason:'Exposição ao ouro para acompanhar teses sobre juros reais, dólar e demanda por proteção.',risk:'Ouro não gera caixa; taxas reduzem o patrimônio por cota ao longo do tempo.',source:'SPDR Gold Shares',url:'https://www.spdrgoldshares.com/'},
];

export const MARKET_VIEWS = [
  {asset:'MSFT · Microsoft',type:'Ação',date:'2026-09-22',author:'Oppenheimer, reportado pela Reuters',title:'Expectativa de aceleração em nuvem e IA',reason:'A casa destacou monetização do Copilot, capacidade de computação e adoção empresarial. Elevou seu alvo para US$ 570; o potencial de cerca de 14% citado refere-se ao fechamento usado naquela publicação.',risk:'É uma opinião datada de uma casa, não consenso permanente. Gastos de capital, concorrência e margens podem frustrar o cenário.',url:'https://www.schwab.wallst.com/schwab/Prospect/research/stocks/news.asp?doc=3200-nL4N45E0OI-1&symbol=MSFT'},
  {asset:'Crédito imobiliário comercial / CMBS',type:'Renda fixa privada',dateLabel:'Edição 2026 · início do ano',author:'LSEG · Year-Ahead Outlook 2026',title:'Cenário condicional para crédito imobiliário',reason:'A análise considera que redução de juros e financiamento mais estável poderiam apoiar a demanda e reduzir spreads.',risk:'Cenário de início de ano, não visão atual: depende de juros, inflação, crédito e mercado imobiliário. Não é indicação de um título específico.',url:'https://www.lseg.com/content/dam/lseg/en_us/documents/reports/2026-year-ahead-outlook.pdf'},
  {asset:'Ouro e metais preciosos',type:'Commodities',dateLabel:'Abril de 2026',author:'Banco Mundial · Commodity Markets Outlook',title:'Demanda de proteção e compras oficiais',reason:'O relatório discute suporte de demanda por proteção e bancos centrais, com riscos de alta no cenário de metais preciosos.',risk:'Cenário de abril: alívio geopolítico e menor compra oficial podem enfraquecer o suporte. Não é promessa de valorização.',url:'https://thedocs.worldbank.org/en/doc/f3138644a1e8e2bb631399ae11d6c408-0050012026/original/CMO-April-2026.pdf'},
];

export function rankRadar(items,metric){
  const groups=new Map();
  for(const item of items){
    if(!Number.isFinite(item[metric])||!item.asOf||!item.method)continue;
    const key=[item.type,item.currency,item.asOf,item.method].join('|');
    if(!groups.has(key))groups.set(key,[]);
    groups.get(key).push(item);
  }
  return [...groups.values()].map(group=>group.sort((a,b)=>b[metric]-a[metric]));
}
