import {useCallback,useEffect,useRef,useState} from 'react';
import {Title,External} from './ui';
import {date,fmt} from './format';
import {parseCSV,normalizeSearch} from './finance';
import {CLASSES,WATCHLIST,MARKET_VIEWS,rankRadar} from './radar';

const initial=WATCHLIST.map(a=>({...a,...a.observation,sourceKind:a.observation?'Observação oficial datada':'Catálogo para pesquisa'}));
const pct=value=>Number.isFinite(value)?`${fmt(value)}%`:'Não disponível';

export default function Radar({snapshot,onEducation}){
  const [items,setItems]=useState(initial),[tab,setTab]=useState('watch'),[group,setGroup]=useState('Todas'),[currency,setCurrency]=useState('Todas'),[query,setQuery]=useState(''),[sort,setSort]=useState('r5'),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[ticker,setTicker]=useState(''),[selected,setSelected]=useState('SCHD');
  const requested=useRef(new Set()),running=useRef(false);
  const api=import.meta.env.VITE_API_URL;
  const load=useCallback(async symbols=>{
    if(running.current)return;
    if(!api){setMessage('Esta edição pública não redistribui cotações Yahoo. Para ampliar o radar, importe históricos CSV ou execute o conector pessoal local descrito no README. As observações oficiais abaixo continuam disponíveis.');return;}
    running.current=true;setBusy(true);setMessage('Consultando a fonte pessoal…');let good=0,bad=0;
    for(const symbol of symbols.slice(0,12)){
      try{
        const response=await fetch(`${api}/api/assets/radar?ticker=${encodeURIComponent(symbol)}`,{signal:AbortSignal.timeout(90000)});
        const data=await response.json();if(!response.ok)throw new Error(data.detail||'Fonte indisponível');
        if(!data.symbol||!data.currency||!data.asOf)throw new Error('Dados incompletos');
        requested.current.add(data.symbol);good++;
        setItems(old=>{const previous=old.find(a=>a.symbol===data.symbol);const value={...previous,...data,type:previous?.type||data.type,sourceKind:'Consulta pessoal',income:Number.isFinite(data.incomeTTM)&&data.incomeTTM>0};return [...old.filter(a=>a.symbol!==data.symbol),value];});
      }catch{bad++;}
    }
    setMessage(`${good} consultas concluídas; ${bad} indisponíveis. Dados anteriores preservados, com suas datas.`);setBusy(false);running.current=false;
  },[api]);
  useEffect(()=>{if(!api)return;const start=setTimeout(()=>load(['SCHD','VIG','MSFT','ITUB4.SA']),0);const timer=setInterval(()=>load([...requested.current]),15*60000);return()=>{clearTimeout(start);clearInterval(timer);};},[api,load]);
  const filtered=items.filter(a=>(group==='Todas'||a.type===group)&&(currency==='Todas'||a.currency===currency)&&normalizeSearch(`${a.symbol} ${a.name}`).includes(normalizeSearch(query)));
  const groups=rankRadar(filtered,sort);
  const importHistory=async event=>{
    try{
      const file=event.target.files[0];if(!file)return;if(file.size>2e6)throw new Error('Limite de 2 MB por CSV.');
      const rows=parseCSV(await file.text());const start=rows[0],end=rows.at(-1);const years=(Date.parse(end.date)-Date.parse(start.date))/86400000/365.25;
      if(years<.98||years>1.02)throw new Error('Para o radar, importe aproximadamente um ano (359–372 dias). O ranking separa janelas exatas e não soma dividendos.');
      const asset=items.find(a=>a.symbol===selected);if(!asset)throw new Error('Selecione um ativo do catálogo.');
      const value={...asset,r1:(end.close/start.close-1)*100,r3:null,r5:null,asOf:end.date,method:`CSV · preço informado · ${start.date} a ${end.date}`,sourceKind:'Histórico importado',source:file.name,url:null,observation:null,incomeTTM:null,yieldTTM:null,analyst:null,income:null,payment:null};
      setItems(old=>old.map(a=>a.symbol===selected?value:a));setSort('r1');setMessage('Histórico importado. Não informa proventos nem opinião de analistas.');
    }catch(error){setMessage(error.message);}event.target.value='';
  };
  const views=MARKET_VIEWS.filter(v=>(group==='Todas'||v.type===group)&&normalizeSearch(`${v.asset} ${v.title} ${v.author}`).includes(normalizeSearch(query)));
  return <>
    <Title eyebrow="OBSERVAR, VERIFICAR, ENTENDER" title="Radar de ativos e rendimentos" description="Crescimento histórico, renda distribuída e teses publicadas. Seleção inicial de pesquisa, sem classificação universal de melhores investimentos."><button className="secondary" onClick={onEducation}>Finalidade educativa</button></Title>
    <div className="notice"><strong>Somente para fins educativos.</strong> Rentabilidade passada, dividendos e preços-alvo não garantem resultados futuros. Cada destaque informa o motivo, a fonte e os riscos.</div>
    <div className="tabs">{[['watch','Lista para acompanhar'],['growth','Crescimento histórico'],['income','Renda e distribuições'],['views','Expectativas do mercado'],['classes','Todas as classes']].map(([id,name])=><button key={id} className={tab===id?'active':''} onClick={()=>setTab(id)}>{name}</button>)}</div>
    <div className="toolbar"><input aria-label="Buscar no radar" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Ativo, código ou tese…"/><select aria-label="Classe no radar" value={group} onChange={e=>setGroup(e.target.value)}><option>Todas</option>{CLASSES.map(([name])=><option key={name}>{name}</option>)}</select><select aria-label="Moeda no radar" value={currency} onChange={e=>setCurrency(e.target.value)}>{['Todas','BRL','USD','EUR','GBP','AUD'].map(c=><option key={c}>{c}</option>)}</select></div>
    {tab!=='classes'&&<div className="panel"><h3>Amplie sua lista de pesquisa</h3><p>Consulte qualquer código atendido pela fonte, inclusive fundos e outras classes. Produtos privados, renda fixa individual e contratos sem histórico público podem não ter cobertura. Dados de classes desconhecidas ficam identificados.</p><div className="toolbar"><input aria-label="Código para consultar no radar" placeholder="Ex.: AAPL, BOVA11.SA, BTC-USD" value={ticker} onChange={e=>setTicker(e.target.value)}/><button disabled={busy||!ticker.trim()} onClick={()=>load([ticker.trim().toUpperCase()])}>Consultar · conector pessoal</button><button className="secondary" disabled={busy} onClick={()=>load(filtered.map(a=>a.symbol))}>{busy?'Consultando…':'Atualizar lista · local'}</button></div><details><summary>Comparar um histórico CSV sem conector</summary><p>Colunas date e close, ou data e preço, aproximadamente um ano. Confirme a moeda e o tratamento de proventos antes de importar.</p><div className="toolbar"><select aria-label="Ativo do CSV no radar" value={selected} onChange={e=>setSelected(e.target.value)}>{items.map(a=><option key={a.symbol} value={a.symbol}>{a.symbol} · {a.currency}</option>)}</select><label className="upload">Importar histórico<input type="file" accept=".csv" aria-label="Importar histórico no radar" onChange={importHistory}/></label></div></details><p role="status">{message}</p></div>}
    {tab==='growth'&&<><div className="toolbar"><label>Ordenar por <select aria-label="Período do ranking" value={sort} onChange={e=>setSort(e.target.value)}><option value="r1">1 ano acumulado</option><option value="r3">3 anos anualizados</option><option value="r5">5 anos anualizados</option></select></label></div><p>Ordem decrescente somente dentro de cada grupo comparável. Retornos positivos indicam crescimento no período observado, não uma sequência ininterrupta de altas. A amostra não cobre todo o mercado.</p>{groups.map((rows,index)=><div className="panel" key={index}><h3>{rows[0].type} · {rows[0].currency} · {date(rows[0].asOf)}</h3><p className="muted">{rows[0].method}</p><div className="table-scroll"><table><thead><tr><th>Ativo</th><th>1 ano</th><th>3 anos a.a.</th><th>5 anos a.a.</th><th>Leitura</th><th>Fonte</th></tr></thead><tbody>{rows.map(a=><tr key={a.symbol}><td>{a.symbol}</td><td>{pct(a.r1)}</td><td>{pct(a.r3)}</td><td>{pct(a.r5)}</td><td>{a[sort]>0?'Cresceu no período':a[sort]<0?'Caiu no período':'Sem variação'}</td><td>{a.url?<External href={a.url}>{a.source}</External>:a.source}</td></tr>)}</tbody></table></div>{rows.length===1&&<p className="muted">Só um histórico neste grupo: não há comparação relativa nem vencedor.</p>}</div>)}{!groups.length&&<p className="empty">Não há históricos comparáveis para esta seleção. Consulte a fonte ou importe um CSV.</p>}</>}
    {(tab==='watch'||tab==='income')&&<><p className="muted">Referências editoriais verificadas em 03/10/2026; não são atualizadas automaticamente. Métricas locais exibem a própria data. Ausência de pagamento informado não comprova que o ativo nunca distribui renda.</p><div className="sources-grid">{filtered.filter(a=>tab==='watch'||a.income===true).map(a=><article className="source-card" key={a.symbol}><span className="eyebrow">{a.type} · {a.currency} · {a.country||'País não informado'}</span><h3>{a.symbol} · {a.name}</h3><span className="tag">{a.sourceKind}</span><p><strong>Por que observar: </strong>{a.reason||'Confira os retornos medidos e os pagamentos informados pela fonte; não há tese individual documentada.'}</p><div className="radar-facts"><span>1 ano: <strong>{pct(a.r1)}</strong></span><span>5 anos a.a.: <strong>{pct(a.r5)}</strong></span>{Number.isFinite(a.yieldTTM)&&<span>Distribuição 12m / fechamento bruto: <strong>{pct(a.yieldTTM)}</strong></span>}{Number.isFinite(a.payment)&&<span>Pagamento documentado: <strong>{a.currency} {fmt(a.payment,4)} · {date(a.paymentDate)}</strong></span>}</div><p className="muted">{a.asOf?`Histórico até ${date(a.asOf)}. ${a.method}`:'Rentabilidade ainda não medida: não classificado como crescimento ou mais rentável.'}{a.fetchedAt&&` Consulta: ${date(a.fetchedAt)}.`}</p>{a.payments?.length>0&&<details><summary>Distribuições informadas nos últimos 12 meses</summary><ul>{a.payments.map(p=><li key={p.date}>{date(p.date)} · {a.currency} {fmt(p.amount,4)} por unidade, bruto</li>)}</ul><p>Datas e valores conforme a fonte; não separar JCP, dividendos especiais e demais rubricas sem o documento do emissor.</p></details>}<p><strong>Risco / contraponto: </strong>{a.risk||'Dados históricos não avaliam todos os riscos, custos, liquidez e tributação.'}</p>{a.analyst&&<p>Alvo médio agregado: {a.currency} {fmt(a.analyst.target)} · {a.analyst.count} analistas · diferença para fechamento consultado {pct(a.analyst.upside)}. {a.analyst.notice}</p>}{a.url&&<External href={a.url}>{a.source}</External>}</article>)}</div>{!filtered.filter(a=>tab==='watch'||a.income===true).length&&<p className="empty">Nenhum ativo com distribuição documentada ou política de renda nesta seleção.</p>}</>}
    {tab==='views'&&<><p>Opiniões atribuídas e datadas; cenários diferentes podem divergir. Nenhum número abaixo representa ganho garantido, consenso de todos os participantes ou avaliação própria do aplicativo.</p><div className="sources-grid">{views.map(v=><article className="source-card" key={v.asset}><span className="eyebrow">{v.type} · {v.dateLabel||date(v.date)}</span><h3>{v.asset}</h3><strong>{v.title}</strong><p><strong>Autor: </strong>{v.author}</p><p><strong>Por quê: </strong>{v.reason}</p><p><strong>O que pode contrariar: </strong>{v.risk}</p><External href={v.url}>Publicação original</External></article>)}</div>{!views.length&&<p className="empty">Nenhuma tese verificada nesta seleção. Não foi inventado consenso.</p>}<div className="panel"><h3>Novas manchetes para investigar</h3><p>Links da edição automática, sem transformar títulos em sinais ou atribuir uma tese que o artigo não documenta.</p>{(snapshot.news||[]).filter(n=>/dividend|dividendo|rendimentos|price target|preço.alvo|upside|valuation/i.test(n.title)).slice(0,8).map(n=><p key={n.id}><External href={n.url}>{n.title}</External><small> · {n.source} · {date(n.date)}</small></p>)}</div></>}
    {tab==='classes'&&<div className="sources-grid">{CLASSES.map(([name,income,check])=><article className="source-card" key={name}><h3>{name}</h3><p><strong>Forma de renda: </strong>{income}</p><p><strong>Por que observar / investigar: </strong>{check}</p><p className="muted">Cobertura quantitativa depende da fonte e do produto. Sem histórico, regulamento ou pesquisa atribuída, não há ranking, yield ou expectativa estimada.</p><button className="secondary" onClick={()=>{setGroup(name);setTab('watch');}}>Ver ativos desta classe</button></article>)}</div>}
  </>;
}
